version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: circleci/node:18
    working_directory: ~/repo
    environment:
      NODE_VERSION: 18
    steps:
      - checkout
      - run: yarn run build

  test:
    docker:
      - image: circleci/node:18
    working_directory: ~/repo
    environment:
      NODE_VERSION: 18
    steps:
      - checkout
      - run: yarn run lint
      - run: yarn run tsc
      - run: yarn run test
      - run: yarn playwright install --with-deps
      - run: yarn run test:e2e

workflows:
  sample:
    jobs:
      - node/test:
          version: '18.15'
          pkg-manager: yarn
